"""init

Revision ID: dd5c53de6475
Revises: cc737774299d
Create Date: 2026-06-22 15:58:34.548776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd5c53de6475'
down_revision: Union[str, Sequence[str], None] = 'cc737774299d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('tasks_manager_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'])
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'price')
    op.drop_column('tasks', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_manager_id_fkey'), 'tasks', 'users', ['manager_id'], ['id'])
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('tasks', 'creator_id')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
